site_name: Unofficial OSSM Documentation

nav: 
  - Home: index.md
  - FAQ: faq.md
  - Bill of materials:
    - Index: assembly/bom.md
    - 3D Printed Parts: assembly/3dprintedparts.md
  - Assembly instructions:
    - Index: assembly/index.md
    - Hardware: assembly/hardware_assembly.md
    - Electronics: assembly/electronics.md
  - Mounting:
    - Index: mounting/index.md
  - R+D Reference Boards:
    - Index: boards/index.md
    - V1.0: boards/v1.0.md
    - V2.0: boards/v2.0.md
    - V2.1: boards/v2.1.md
    - V2.2: boards/v2.2.md
    - V2.3: boards/v2.3.md
    - V3.0: boards/v3.0.md
  - OSSM Electronics:
    - Index: electronics/index.md
    - Custom Boards: electronics/custom-board.md
    - M5 Remote: electronics/m5.md
  - Software, Mainline: 
    - Index: software/index.md
    - PlatformIO: software/PlatformIO.md
  - Software, Branches: 
    - Index: software/branches.md
  - Motors: 
    - Index: motors/index.md
    - IHSV57: motors/ihsv57.md
    - 57AIM30 (Gold Motor): motors/57AIM30.md
  - Design Decisions:
    - Index: design/index.md
    - MCU: design/mcu.md
    - Motor: design/motor.md
    - Voltage: design/voltage.md
    - Sensorless Homing: design/homing.md
    - Custom PCB: design/PCB.md
  - Safety:
    - OSSM Hazard analysis: hazards.md
    - OSSM Safety considerations: safety.md

theme:
  name: terminal
  palette: gruvbox_dark
  features:
    - navigation.side.indexes
    - navigation.top.hide

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.highlight:
      use_pygments: true
      pygments_style: github-dark
      noclasses: true
  - pymdownx.inlinehilite
  - attr_list

repo_url: https://github.com/KaDargo1984/ossm-docs